# Slatis Nyx Deuteranopia
background #000000
foreground #cdcecd
cursor #4589ff
cursor_text_color #000000
selection_background #4589ff
selection_foreground #cdcecd
url_color #78a9ff

color0 #2c2e2d
color1 #ec8e2c
color2 #a5d6ff
color3 #ffc981
color4 #4589ff
color5 #c9a3f0
color6 #79c0ff
color7 #cdcecd
color8 #626463
color9 #fdac54
color10 #cae8ff
color11 #ffc981
color12 #78a9ff
color13 #d8bcf7
color14 #a5d6ff
color15 #ffffff
