# Slatis Nyx Mono
background #000000
foreground #adbac7
cursor #4589ff
cursor_text_color #000000
selection_background #4589ff
selection_foreground #adbac7
url_color #78a9ff

color0 #2c2e2d
color1 #e97871
color2 #42be65
color3 #f2c86c
color4 #4589ff
color5 #c9a3f0
color6 #5ec8e5
color7 #adbac7
color8 #636e7b
color9 #ff9e96
color10 #6fdc8c
color11 #f1c21b
color12 #78a9ff
color13 #d8bcf7
color14 #91dbf2
color15 #cdd9e5
