# Slatis Nyx High Contrast
background #000000
foreground #f0f3f6
cursor #71b7ff
cursor_text_color #000000
selection_background #71b7ff
selection_foreground #f0f3f6
url_color #91cbff

color0 #6e7681
color1 #ff9492
color2 #4ae168
color3 #ffcf86
color4 #71b7ff
color5 #c9a3f0
color6 #91cbff
color7 #f0f3f6
color8 #bdc4cc
color9 #ffb1af
color10 #72f088
color11 #ffcf86
color12 #91cbff
color13 #d8bcf7
color14 #addcff
color15 #ffffff
