# Slatis Nyx Tritanopia
[colors.primary]
background = "#000000"
foreground = "#cdcecd"

[colors.cursor]
cursor = "#4589ff"
text = "#000000"

[colors.selection]
background = "#4589ff"
text = "#cdcecd"

[colors.normal]
black = "#2c2e2d"
red = "#ff7b72"
green = "#a5d6ff"
yellow = "#ffc1ba"
blue = "#4589ff"
magenta = "#c9a3f0"
cyan = "#79c0ff"
white = "#cdcecd"

[colors.bright]
black = "#626463"
red = "#ffa198"
green = "#cae8ff"
yellow = "#ffc1ba"
blue = "#78a9ff"
magenta = "#d8bcf7"
cyan = "#a5d6ff"
white = "#ffffff"
